export const ALL_COLORS = [
    "rosybrown",
    "indianred",
    "red",
    "tomato",
    "coral",
    "darkorange",
    "orange",
    "khaki",
    "gold",
    "royalblue",
    "cornflowerblue",
    "skyblue",
    "aquamarine",
    "mediumaquamarine",
    "mediumseagreen",
    "yellowgreen",
    "lightgreen",
    "dimgray",
    "lightgray",
    "thistle",
    "pink",
    "plum",
    "orchid",
    "mediumpurple",
    "lavender",
] as const;

export type Colors = typeof ALL_COLORS[number];